### PR TITLE
Adds Support for Mada.

### LINKED ISSUE #42: Add credit card type: MADA(SAUDI)
Would be nice if we can add support for Mada(The major payment system in the kingdom of Saudi Arabia). Attached the Bin List. 
[mada.bin.list.for.e-commerce.pdf](https://github.com/bendrucker/creditcards-types/files/2949989/mada.bin.list.for.e-commerce.pdf)

### PR DESCRIPTION
**Pull request by shirazz**
Fixes #42

### CODE REVIEW

**Comment by shirazz** [comment]
@bendrucker can you please have a look and let me know your inputs especially with regards to the eager pattern.

**Comment by shirazz** [comment]
Thank you for reviewing the code @bendrucker.

> Sounds like these are all Visa/Mastercards and identifying a card as mada that was previously visa/mastercard may break things for users.

Yea. These are all visa and master card but co-branded. To be honest, I am not sure about how this will break the current users. Since I am using a more stricter Regex, to determine the card type, I believe it should be okay.

> I'm ok including this type for people to require and use if they wish.

This means this PR won't be merged and if any of the users need the changes they have to fork and merge this to their respective repo? Please correct me if I am wrong.

**Comment by bendrucker** [comment]
> To be honest, I am not sure about how this will break the current users.

Users write validation code that tells the user only Visa/MasterCard/etc are allowed. Previously a card returned its type as Visa. Now it comes back as Mada and fails validation. Same input, different output. It wasn't a bug to return these cards as Visa/MC originally so it's a breaking change to the behavior.

> This means this PR won't be merged and if any of the users need the changes they have to fork and merge this to their respective repo?

The module would be available/documented as optional and users could include as follows:

```js
var types =[require('creditcards-types/types/mada')].concat(require('creditcards-types'))
```

No forking required, but users would have to opt in.

**Comment by shirazz** [comment]
@bendrucker can you please review my changes.

**Comment by bendrucker** [comment]
Thanks! I'm on vacation currently but will come back to this.

**Comment by bendrucker** [comment]
Sorry for the delay, touched up the readme and merged

**Comment by shirazz** [comment]
Thanks @bendrucker.

**Comment by nicolas-maalouf-cko** [comment]
Hi @bendrucker @shirazz 

We're using this project for one of our solutions and we noticed that the regex used for Mada cards actually includes non-Mada Visa / MasterCard card BINs.

An example is "465943" which is a UK issued Visa card, so it's creating confusion in some situations.

There's also a new more up-to-date list of BINs that you can find here:
https://docs.checkout.com/docs/mada#section-processing-payments-with-frames-and-checkout-js

I've generated a regex that seems to exclusively match all the updated BIN list:

/4(0(0861|1757|7(197|395)|9201)|1(0685|7633|9593)|2(281(7|8|9)|8(331|67(1|2|3)))|3(1361|2328|4107|9954)|4(0(533|647|795)|5564|6(393|404|672))|5(5(036|708)|7865|8456)|6(2220|854(0|1|2|3))|8(301(0|1|2)|4783|609(4|5|6)|931(7|8|9))|93428)|5(0(4300|8160)|13213|2(1076|4(130|514)|9(415|741))|3(0906|1095|2013|5(825|989)|6023|7767|9931)|4(3(085|357)|9760)|5(4180|7606|8848)|8(5265|8(8(4(5|6|7|8|9)|5(0|1))|98(2|3))|9(005|206)))|6(0(4906|5141)|36120)|9682(0(1|2|3|4|5|6|7|8|9)|1(0|1))/

I'm sure there's room to improve it, would be great if anyone can assist before I send a pull request.
Also I'm unsure on how to deal  with pattern vs. eagerPattern.

Thanks a lot

**Pull request closed without merging**
