### PR TITLE
Regex Elo credit Card created.

### PR DESCRIPTION
**Pull request by jairorudas**
Regex Created for the Elo Brazilian credit card.

### CODE REVIEW

**Comment by bendrucker** [comment]
The tests are failing. Seems like this won't be possible without asking users to prioritize/weight cards which I've been trying to avoid.

**Comment by jairorudas** [comment]
Hi!. The tests passed! and now, wich is the next step for use the new credit card in **_angular-credit-cards_**?

**Comment by bendrucker** [comment]
Hey, that's awesome! Can I get a link to the official documentation you used to choose those ranges?

**Comment by jairorudas** [comment]
Hi!! I have a document that the bank sent to me. I'm sending here.
have a nice week!

[RANGE_DE_BINS_ ELO_POR_PRODUTO (V.20170324) (002).pdf](https://github.com/bendrucker/creditcards-types/files/1427243/RANGE_DE_BINS_.ELO_POR_PRODUTO.V.20170324.002.pdf)

**Comment by bendrucker** [comment]
This is excellent, thank you! I want to put in a bit of work on these credit card libraries this week. In particular I want to build up an archive of card issuer documentation and enable people to add custom cards and assign certain types priority when there's overlap.

Just left my day job a few days ago so I'll have some time to devote to open source during the week.

Thanks again for this, I'll merge and update this thread later in the week.

**Comment by jairorudas** [comment]
Ben, that is exclent!! thank you so much!!

**Comment by bendrucker** [comment]
Sorry for the long delay in getting this merged! I'm releasing a significant breaking refactor that I've been working on in parts. It breaks up the card types into individual modules, both for definitions and tests. This will make it easier to add new types while offering users the choice to only depend on a handful of card types. I've included Elo in this release.

**Comment by bendrucker** [comment]
I've been working on a new version of creditcards in parallel with the knowledge that users will want to pass in a custom array of card types for card number/CVC validation. I'll push out a major for that today as well. It may be a little longer until I get to the Angular side of things.

**Pull request closed without merging**
